{% set version = "4.3.1" %}

package:
  name: astroid
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/a/astroid/astroid-{{ version }}.tar.gz
  sha256: bb359253d8ced6635a3881c17ebcbbc0e0b65ca23b555a9bd03c92a3cbf4caa7

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - setuptools >=77
    - pip
  run:
    - python
    - typing_extensions >=4      # [py<311]

test:
  requires:
    - pip
  imports:
    - astroid
    - astroid.modutils
  commands:
    - python -m pip check

about:
  home: https://www.astroid.org/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: A abstract syntax tree for Python with inference support.
  description: |
    Astroid provide a common base representation of python source code for
    projects such as pychecker, pyreverse, pylint.
  doc_url: http://astroid.readthedocs.io/en/latest/?badge=latest
  doc_source_url: https://github.com/pylint-dev/astroid/blob/master/doc/index.rst
  dev_url: https://github.com/pylint-dev/astroid

extra:
  recipe-maintainers:
    - wshanks
    - timkpaine
    - jakirkham
    - ocefpaf
