{% set version = "2.8.5" %}

package:
  name: astroid
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/astroid/astroid-{{ version }}.tar.gz
  sha256: 11f7356737b624c42e21e71fe85eea6875cb94c03c82ac76bd535a0ff10b0f25

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - pytest-runner
    - setuptools_scm
  run:
    - python
    - setuptools >=20.0
    - lazy-object-proxy >=1.4.0
    - wrapt >=1.11,<1.13
    - typed-ast >=1.4.0,<1.5  # [py<38]
    - typing-extensions >=3.10  # [py<=39]

test:
  requires:
    - pip
  imports:
    - astroid
    - astroid.modutils
  commands:
    - python -m pip check

about:
  home: https://www.astroid.org/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: A abstract syntax tree for Python with inference support.
  description: |
    Astroid provide a common base representation of python source code for
    projects such as pychecker, pyreverse, pylint.
  doc_url: http://astroid.readthedocs.io/en/latest/?badge=latest
  doc_source_url: https://github.com/PyCQA/astroid/blob/master/doc/index.rst
  dev_url: https://github.com/PyCQA/astroid

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
