{% set version = "2.14.2" %}

package:
  name: astroid
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/astroid/astroid-{{ version }}.tar.gz
  sha256: a3cf9f02c53dd259144a7e8f3ccd75d67c9a8c716ef183e0c1f291bc5d7bb3cf

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - lazy-object-proxy >=1.4.0
    - typing-extensions >=4.0.0
    - typed-ast <2.0,>=1.4.0  # [py<38]
    - wrapt <2,>=1.11
    - setuptools >=20.0

test:
  requires:
    - pip
  imports:
    - astroid
    - astroid.modutils
  commands:
    - python -m pip check

about:
  home: https://www.astroid.org/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: A abstract syntax tree for Python with inference support.
  description: |
    Astroid provide a common base representation of python source code for
    projects such as pychecker, pyreverse, pylint.
  doc_url: http://astroid.readthedocs.io/en/latest/?badge=latest
  doc_source_url: https://github.com/PyCQA/astroid/blob/master/doc/index.rst
  dev_url: https://github.com/PyCQA/astroid

extra:
  recipe-maintainers:
    - wshanks
    - timkpaine
    - jakirkham
    - ocefpaf
