{% set version = "3.3.8" %}

package:
  name: astroid
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/astroid/astroid-{{ version }}.tar.gz
  sha256: a88c7994f914a4ea8572fac479459f4955eeccc877be3f2d959a33273b0cf40b

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - setuptools >=75.2.0
    - pip
  run:
    - python
    - typing_extensions >=4.0.0  # [py<311]

test:
  requires:
    - pip
  imports:
    - astroid
    - astroid.modutils
  commands:
    - python -m pip check

about:
  home: https://www.astroid.org/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: A abstract syntax tree for Python with inference support.
  description: |
    Astroid provide a common base representation of python source code for
    projects such as pychecker, pyreverse, pylint.
  doc_url: http://astroid.readthedocs.io/en/latest/?badge=latest
  doc_source_url: https://github.com/PyCQA/astroid/blob/master/doc/index.rst
  dev_url: https://github.com/PyCQA/astroid

extra:
  recipe-maintainers:
    - wshanks
    - timkpaine
    - jakirkham
    - ocefpaf
