schema_version: 1

context:
  version: "4.3.1"

package:
  name: astroid
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/a/astroid/astroid-${{ version }}.tar.gz
  sha256: bb359253d8ced6635a3881c17ebcbbc0e0b65ca23b555a9bd03c92a3cbf4caa7

build:
  number: 2
  skip: match(python, "<3.10")
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
  host:
    - python
    - setuptools >=77
    - pip
  run:
    - python
    - if: match(python, "<3.11")
      then: typing_extensions >=4

tests:
  - python:
      imports:
        - astroid
        - astroid.modutils
      pip_check: true

about:
  license: LGPL-2.1-or-later
  license_file: LICENSE
  summary: A abstract syntax tree for Python with inference support.
  description: |
    Astroid provide a common base representation of python source code for
    projects such as pychecker, pyreverse, pylint.
  homepage: https://www.astroid.org/
  repository: https://github.com/pylint-dev/astroid
  documentation: http://astroid.readthedocs.io/en/latest/?badge=latest

extra:
  recipe-maintainers:
    - wshanks
    - timkpaine
    - jakirkham
    - ocefpaf
